# -*- coding: utf-8 -*-
"""Learn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RIqWWfJ9UuVx9J9nRfK3RM3hK-0UD5XA
"""

#This is introduction to Python
print("Fuck Python")
print(120)

x = 3+8
print(x)

print("This is x:", x)

"""Application: Comments.py
  Written by: Macintosh
  Purpose: Show how to use comments.

About nymeric types
Binary
Octal
Decimal
Hexadecimal
"""

#Integers
Test = 0b100
print("100 Binary:", Test)

Test = 0o100
print("100 Octal:", Test)

Test = 100
print("100 Decimal:", Test)

Test = 0x100
print("100 Hexadecimal", Test)

print(bin(Test)) #bin: 2
print(oct(Test)) #oct: 8
print(hex(Test)) #hex : 16

"""# Variable's type
int() --> จำนวนเต็ม

float() --> ทศนิยม

What's string? -
"""



print(ord("A"))

myInt = int("123")
print("myInt")

print(type(myInt))


myStr = str(1234.56)
print(myStr)
print(type(myStr))

"""# Date and Times"""

import datetime
print(datetime.datetime.now ())
print(datetime.datetime.now() .date())